[project]
name = "QuestCompleter"
version = "0.1.0"
description = "A simple discord quest completer written in python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "pydotmap>=0.1.3",
    "rich>=14.2.0",
]
