name: Format
run-name: ${{ github.actor }} is formating...

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      # Setup python enviorment
      - name: Setting up Python
        uses: actions/setup-python@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Ruff-ing (formating)
      # it only formats because that's the only thing i want
      - name: Formating...
        run: |
          ruff format --check
